= Conclusiones <cap-conclusiones>

== Respuesta a la pregunta del trabajo

El trabajo partió de una pregunta concreta: si una previsión de irradiancia y de precio basada en redes LSTM mejora un sistema de gestión de energía heurístico para una estación de repostaje multi-energía. La respuesta se descompone en tres resultados, todos ellos medidos.

La previsión, inyectada en las reglas de la heurística, no reduce el coste. La variante predictiva quedó indistinguible de la heurística en coste: la diferencia media es de una décima de euro sobre un recibo diario de unos 45 € en la métrica principal, no significativa y muy por debajo de la dispersión entre semillas. Esto se cumple tanto con la previsión real como con la perfecta. Llegar a ese empate exigió dimensionar la regla: una primera implementación que convertía «el precio va a subir» en una acción de magnitud fija empeoraba el coste, y lo empeoraba más cuanto mejor era la previsión, lo que muestra que el resultado depende de cómo la regla usa la previsión, no solo de su exactitud. Sí superó a la heurística de forma sistemática en la seguridad de suministro de hidrógeno: todas las variantes predictivas evaluadas mantuvieron el tanque de alta más lleno y redujeron el tiempo en nivel crítico, con una mejora que crece más de diez veces al pasar de la previsión real a la perfecta. La aportación medible de la predicción en este montaje está en el servicio de hidrógeno, no en el coste, y sobre todo en el día nublado, que es a la vez donde anticiparse vale más y donde el modelo de precio es peor.

El margen económico estaba en usar la batería para el electrolizador, y no necesitaba previsión. Al medir a dónde iba cada kilovatio-hora importado apareció el punto débil de la heurística heredada: entre el 74 % y el 78 % de la electricidad que compraba a la red era para el electrolizador, y en los instantes de compra la batería estaba al 85 % de media. La lógica servía la carga de los vehículos desde la batería y, en un paso posterior, encendía el electrolizador contra la red. La Versión C cambia ese orden (ofrece esa carga a la batería antes que a la red) y programa la producción de hidrógeno en las horas más baratas del horizonte sobre el precio ya publicado. Sobre siete días y veinte pares escenario-semilla reduce el coste total con hidrógeno en 52,3 € por semana de media (un 13,9 % del recibo, mejor en los veinte pares, $p = 9,6 dot 10^(-5)$), importa un 54 % menos energía y eleva la autosuficiencia del 87,7 % al 94,3 %. De esa mejora, 47,1 € proceden de ese cambio de orden y 5,1 de la programación; esta segunda cifra es significativa pero inferior al umbral de relevancia de 9,3 € fijado de antemano.

Añadir la red neuronal de precio a la Versión C no cambió ningún resultado. La tanda que la sustituye por la persistencia de 24 horas produjo exactamente los mismos veinte resultados, KPI por KPI. La razón es que la información que la decisión necesita ya está disponible: el mercado diario publica a las 13:00 el precio del día siguiente, y las horas que quedan por prever —la madrugada siguiente, cuando se evalúa por la mañana— no alteran nunca el orden de mérito. La previsión de precio es correcta, pero innecesaria en esta decisión. La previsión solar sí interviene en la Versión C, al estimar el excedente que podrá absorber el electrolizador, pero su contribución queda dentro de los 5,1 € de la programación y no se aisló.

La conclusión general no es que la predicción no sirva: su valor depende de en qué decisión se inserte y de qué información no esté ya disponible. En esta instalación el margen estaba en una decisión que la información instantánea ya permitía tomar (alimentar el electrolizador desde la batería), y la previsión aporta donde hay incertidumbre real, que es el suministro de hidrógeno en los días de poco sol.

== Aportaciones

- Un EMS para la estación OASIS que mejora un 14 % del coste semanal, en los veinte casos evaluados, al heurístico de referencia —que no es una regla ingenua, sino la heurística más avanzada del trabajo antecedente, con reparto dinámico batería-electrolizador, tiempo mínimo de funcionamiento con histéresis y decisión económica de producción ya incorporados—, y lo hace con un cambio de diez líneas en el orden en que se usa la batería y un planificador de orden de mérito que solo usa el orden de los precios y es por tanto insensible a la sub-dispersión de la previsión.
- La identificación y medida de dos defectos del EMS heredado que no estaban documentados: la batería que no alimentaba al electrolizador y el test económico del compresor aplicado al electrolizador, que en el escenario nublado llevaba a producir hidrógeno por encima de su precio de reposición.
- Una cadena de medida para atribuir el valor de una previsión dentro de un controlador: comparación pareada por semilla con test de rangos, oráculo como cota superior, descomposición de la importación por destinos y análisis de contribución por componentes con predicciones declaradas antes de simular. El margen se localizó con esta cadena de medida, no a partir de la pregunta inicial.
- Dos modelos LSTM validados contra líneas base no triviales, con la medida de que un error medio competitivo puede convivir con una señal inservible para decisiones que dependen de la amplitud, y la corrección del despliegue en lazo cerrado de la red de precio.
- La observación, incorporada al diseño, de que en el mercado español el precio del día siguiente es un dato publicado y no algo que predecir, lo que reordena el papel de cualquier modelo de precio en un EMS con horizonte diario.

== Limitaciones

Las principales están declaradas a lo largo del documento y se recogen aquí juntas. El modelo no incluye peajes ni cargos, igual que su antecedente, y las cifras de coste son comparativas, no de facturación. No hay compra externa de hidrógeno modelada; el déficit se valora al precio externo como coste de oportunidad. Los tanques usan la ecuación de los gases ideales, que a los 600 bar del tanque de alta sobrestima en torno a un 45 % la masa almacenada, de modo que la autonomía de hidrógeno observada en simulación es optimista respecto a la de una instalación real. La demanda de hidrógeno se aproxima por analogía con la de vehículos eléctricos, y el planificador la prevé con una media móvil. La irradiancia de la última hora que alimenta la red solar procede de un reanálisis que no está disponible en tiempo real. La degradación de la batería no está modelada: la Versión C cicla 2,2 veces más energía que la heurística y, aunque a 63 ciclos completos al año la vida de la batería la fija el calendario y no el ciclado, el coste marginal de ese ciclado extra queda sin cuantificar (@sec-res-E). La pila de combustible no arranca en ninguna simulación, porque la batería cubre siempre el déficit antes que ella; el trabajo no dice nada del escenario en que aportaría, el modo isla con la batería agotada. El servicio de hidrógeno empeora en el escenario nublado (tiempo en nivel crítico +4,0 puntos, hidrógeno no servido del 1,8 % frente al 0,5 % de la demanda de esa semana), penalización incluida en el coste total pero relevante para la operación. Y la campaña semanal tiene cinco semillas por escenario, suficientes para el tamaño de efecto de la Versión C pero no para diferencias del orden del euro.

== Líneas futuras

1. Aislar la previsión solar con una tanda que la sustituya por la persistencia de cielo claro, igual que se hizo con la de precio. Es la única previsión que decide algo en la Versión C y no está aislada.
2. Fijar un objetivo de inventario del tanque con previsión. El oráculo mostró que anticipar el día nublado lleva el hidrógeno no servido a cero; una regla que eleve el objetivo del tanque la víspera de un día de poca irradiancia es el sitio donde la previsión solar tiene más recorrido, y exige una previsión de demanda de hidrógeno.
3. Corregir el test económico en la regla de emergencia y los otros defectos anotados del EMS heredado, evaluando cada corrección por separado.
4. Sustituir la heurística por un controlador predictivo con horizonte deslizante, en la línea de @bordons2020mpcmicrogrids y @garciatorres2015mpch2, con un valor terminal para la batería y el hidrógeno que evite la posición abierta al final del horizonte. Ese controlador exigiría además ampliar las previsiones a 48 horas, tramo en el que el mercado diario ya no está publicado y la red de precio recuperaría el valor que aquí no ha tenido. La medida de este trabajo acota lo que puede esperarse: con el precio publicado, la ganancia adicional vendría de coordinar batería y electrolizador, no de predecir mejor.
5. Añadir la compra externa de hidrógeno por lotes con puerto propio, que convertiría la decisión de producir en un problema de reposición con coste fijo de pedido, y comprobar la Versión C con una cadena de datos operativa (previsión meteorológica numérica y piranómetro) en lugar de reanálisis.
6. Modelar la degradación de la batería y simular un horizonte anual. Un conteo de ciclos por profundidad de descarga convertiría el ciclado en coste y diría qué parte del 14 % sobrevive; y una simulación de un año completo capturaría la estacionalidad de la irradiancia y del precio que los cuatro escenarios solo muestrean.
7. Someter a las dos versiones a una prueba de estrés de demanda, repitiendo A y C con la demanda de vehículos e hidrógeno multiplicada sobre el horizonte semanal, para comprobar si la ventaja de C se mantiene con más carga o se agota al agotarse la batería. Es la comprobación natural del mecanismo, porque todo el ahorro de C descansa en que la batería tenga energía por encima de la reserva cuando el electrolizador la pide. El paso siguiente es una estación futura: duplicar el tráfico, duplicar con él el número de surtidores para que la espera en cola no sea el cuello de botella, y repetir con el campo fotovoltaico actual y ampliado, que separaría si las reglas siguen siendo válidas cuando la estación crece y cuánta generación local hace falta para que crecer no se traduzca en depender más de la red. La herramienta de simulación admite ya ese barrido sin tocar el modelo: los factores de llegada, el número de surtidores y el número de cadenas del campo fotovoltaico son parámetros de la campaña.
