= Introducción <intro>

== Contexto y motivación

La descarbonización del transporte por carretera es una prioridad de la política energética europea: el sector es responsable de una parte sustancial de las emisiones de gases de efecto invernadero de la Unión y su reducción es una de las líneas de acción del Pacto Verde Europeo @europeangreendeal @eea2023transport. El vehículo eléctrico de batería (EV) es hoy la alternativa consolidada, mientras que el vehículo de célula de combustible de hidrógeno (FCEV) se encuentra en una fase de madurez muy anterior —parque y red de repostaje dos o tres órdenes de magnitud menores @iea2023hydrogen— y orientado a corto plazo al transporte pesado y las flotas de uso intensivo. Ambos dependen, sin embargo, de una infraestructura de repostaje/recarga hoy separada por vector energético. Esta separación fragmenta la inversión y ralentiza el despliegue conjunto @speers2018h2me @fchju2019roadmap.

La estación de repostaje multi-energía (MERS, _Multi-Energy Refueling Station_) responde a esta limitación: integra en una única instalación la generación renovable local, el almacenamiento (eléctrico y de hidrógeno) y los puntos de suministro para ambos tipos de vehículo @tahir2024hybridstation. En España, la Hoja de Ruta del Hidrógeno sitúa explícitamente los corredores de repostaje verde como una de las líneas prioritarias de despliegue de hidrógeno renovable @miteco2020h2, y el elevado recurso solar de regiones como Andalucía favorece el uso de generación fotovoltaica local como fuente primaria de una instalación de este tipo.

El reto técnico de una MERS es de operación, además de dimensionamiento: coordinar en tiempo real el reparto de la energía disponible entre la carga de baterías, la producción de hidrógeno vía electrólisis, el uso de la pila de combustible y la atención a la demanda simultánea de EV y FCEV, todo ello bajo un precio eléctrico horario variable. Esta coordinación es responsabilidad del sistema de gestión energética (EMS, _Energy Management System_) de la instalación. El @cap-estado-arte distingue tres familias de EMS: heurísticas basadas en reglas, control predictivo (MPC) y aprendizaje automático. Las estrategias basadas en reglas siguen siendo las más utilizadas en instalaciones reales por su robustez y su sencillez de implementación, pero su principal debilidad es no incorporar información predictiva sobre generación, demanda o precio, lo que les impide anticiparse a eventos futuros.

Este trabajo parte de un antecedente directo: el EMS heurístico más avanzado desarrollado en el TFM de Molero Almazán @molero2025ems para una microrred híbrida con almacenamiento de hidrógeno, que ya incorpora coordinación dinámica batería-electrolizador según el estado de carga y tiempos mínimos de funcionamiento con histéresis. Ese EMS no llega a incorporar predicción real de ninguna variable, a pesar de dejar puertos preparados para ello, como el propio autor reconoce en sus conclusiones y líneas futuras. Este trabajo fin de grado recoge explícitamente esa línea de continuación: adaptar dicho EMS a la arquitectura de una MERS con carga EV e integrar en él predicciones basadas en redes LSTM de dos de sus variables de entrada más relevantes, la irradiancia solar y el precio spot de la electricidad. Con ello se cuantifica la mejora que aporta la predicción frente a la heurística de partida sin ella.

== Objetivos

=== Objetivo general

Diseñar, simular y comparar estrategias de gestión energética (EMS) para una estación de repostaje multi-energía con generación fotovoltaica, almacenamiento electroquímico y de hidrógeno, y carga de vehículos eléctricos y de hidrógeno, partiendo de una estrategia heurística avanzada de referencia sin predicción y llegando a una versión final cuyos componentes se evalúan por separado, para cuantificar qué parte de la mejora es atribuible a las predicciones basadas en redes LSTM de irradiancia solar y precio eléctrico.

=== Objetivos específicos

1. Caracterizar la demanda de carga de vehículos eléctricos, a partir de un dataset real de sesiones de carga rápida (DESL-EPFL), y generar a partir de ella perfiles de demanda sintéticos, tanto de carga EV como de repostaje de hidrógeno, coherentes con el dimensionamiento de la estación (@cap-datos-ev).

2. Desarrollar y validar dos modelos de predicción basados en redes LSTM: uno para la irradiancia solar y otro para el precio spot de la electricidad, ambos a un horizonte de 24 horas, e integrarlos en el bucle de simulación de Simulink mediante S-Functions (@cap-lstm). El horizonte de 24 horas es suficiente para las decisiones de un EMS de reglas; su ampliación a 48 horas, que sí requeriría un control predictivo, queda propuesta como línea futura.

3. Adaptar el EMS heurístico avanzado de referencia @molero2025ems (coordinación dinámica batería/electrolizador según SOC, tiempo mínimo de funcionamiento con histéresis, compresor, doble almacenamiento de hidrógeno y decisión económica de producción propia frente a compra externa) a la arquitectura y a la escala de la estación de este trabajo, manteniendo la máquina de estados de arranque/parada de los equipos electroquímicos ya existente.

4. Diseñar un EMS que incorpore las predicciones LSTM de irradiancia solar y de precio en la toma de decisiones, iterando sobre la versión de referencia hasta una versión final cuyos componentes puedan evaluarse por separado.

5. Simular las versiones bajo condiciones equivalentes y comparar cuantitativamente su desempeño en coste operativo, aprovechamiento de la generación renovable, seguridad del suministro de hidrógeno y régimen de operación de los equipos, para determinar qué parte de la mejora es atribuible específicamente a la predicción.

== Alcance del trabajo

Este trabajo se limita a la fase de diseño, simulación y comparación en MATLAB/Simulink; no incluye la implementación física de la instalación ni un análisis económico de inversión (CAPEX/OPEX) a largo plazo. El horizonte de simulación considerado es de días/semanas representativos (laborable y fin de semana), no de un año completo, en línea con el enfoque adoptado también en el antecedente de este trabajo @molero2025ems. La ubicación de referencia es Sevilla, lo que condiciona tanto los datos meteorológicos empleados para entrenar el modelo solar como el mercado eléctrico de referencia (OMIE) para el modelo de precio.

Las tres versiones del EMS que se comparan —la heurística de referencia, la variante que inyecta las previsiones en sus reglas y la versión final, esta última evaluada además en dos configuraciones con componentes desactivados— son todas de tipo heurístico (reglas); no se aborda en este trabajo el diseño de un controlador predictivo basado en modelos (MPC), que el trabajo antecedente señala como siguiente paso para instalaciones de este tipo, y que queda propuesto como línea de trabajo futuro. Del mismo modo, se mantienen las limitaciones ya identificadas en los datos de partida: el perfil de demanda de hidrógeno se aproxima por analogía con el de EV, y la predicción solar se valida con datos meteorológicos observados en lugar de una previsión meteorológica operativa real. Ambas se tienen en cuenta al interpretar los resultados de la comparación (véanse @cap-datos-ev y @cap-lstm).

== Estructura del documento

El resto del documento se organiza como sigue. La @cap-estado-arte revisa el contexto tecnológico de las estaciones de repostaje multi-energía, sus componentes principales (generación fotovoltaica, electrólisis PEM, almacenamiento de hidrógeno, pila de combustible, BESS e infraestructura de carga EV) y las estrategias de gestión energética existentes, y sitúa la contribución de este trabajo respecto a ese estado del arte. La @cap-datos-ev describe el dataset de referencia utilizado para caracterizar la demanda de carga EV, la justificación de la potencia del cargador seleccionada y el proceso de generación de los perfiles de demanda sintéticos empleados en la simulación. La @cap-lstm presenta el desarrollo, entrenamiento y validación de los dos modelos LSTM (irradiancia solar y precio eléctrico) y su integración en el modelo de Simulink.

A continuación, el capítulo de Metodología describe el EMS heurístico de referencia, resume lo que enseñó el intento de mejorarlo inyectando las predicciones LSTM en sus reglas, y presenta el diseño del EMS final de este trabajo, la Versión C, junto con la configuración de las simulaciones y el diseño del análisis de contribución. El capítulo de Resultados presenta y discute la comparación cuantitativa. Finalmente, el capítulo de Conclusiones recoge las principales aportaciones del trabajo y propone líneas de continuación futuras.
